apply_scheduler: true
batch_size: 16
ce_ignore_index: -1
dropout_rate: 0.2
encoder_name: distilbert-base-uncased
epsilon: 1.0e-08
fake_label_index: -1
frozen_backbone: false
gan_training: true
label_names:
- comp.sys.mac.hardware
- comp.graphics
- sci.space
- talk.politics.guns
- sci.med
- comp.sys.ibm.pc.hardware
- comp.os.ms-windows.misc
- rec.motorcycles
- misc.forsale
- alt.atheism
- rec.autos
- sci.electronics
- comp.windows.x
- rec.sport.hockey
- rec.sport.baseball
- talk.politics.mideast
- sci.crypt
- soc.religion.christian
- talk.politics.misc
- talk.religion.misc
lr_discriminator: 5.0e-05
lr_generator: 5.0e-05
max_seq_length: 200
multi_gpu: false
noise_size: 100
num_labels: 20
num_train_epochs: 3
num_train_examples: 5772
num_train_steps: 1082
num_warmup_steps_d: 108
num_warmup_steps_g: 0
save_path: weights/best_model.pth
warmup_proportion_d: 0.1
warmup_proportion_g: 0.0