apply_scheduler: true
batch_size: 16
ce_ignore_index: -1
dropout_rate: 0.2
encoder_name: distilbert-base-uncased
epsilon: 1.0e-08
fake_label_index: -1
frozen_backbone: false
gan_training: true
lr_discriminator: 5.0e-05
lr_generator: 5.0e-05
max_seq_length: 200
multi_gpu: false
noise_size: 100
num_labels: 20
num_train_epochs: 3
num_train_examples: 5772
num_train_steps: 1082
num_warmup_steps_d: 108
num_warmup_steps_g: 0
save_path: weights/best_model.pth
warmup_proportion_d: 0.1
warmup_proportion_g: 0.0
